package db;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTradeOrder<M extends BaseTradeOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setChannelCode(java.lang.String channelCode) {
		set("channelCode", channelCode);
	}
	
	public java.lang.String getChannelCode() {
		return getStr("channelCode");
	}

	public void setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
	}
	
	public java.lang.String getOrgCode() {
		return getStr("orgCode");
	}

	public void setMerchCode(java.lang.String merchCode) {
		set("merchCode", merchCode);
	}
	
	public java.lang.String getMerchCode() {
		return getStr("merchCode");
	}

	public void setCouponAmount(java.lang.Long couponAmount) {
		set("couponAmount", couponAmount);
	}
	
	public java.lang.Long getCouponAmount() {
		return getLong("couponAmount");
	}

	public void setUserIncomeAmount(java.lang.Long userIncomeAmount) {
		set("userIncomeAmount", userIncomeAmount);
	}
	
	public java.lang.Long getUserIncomeAmount() {
		return getLong("userIncomeAmount");
	}

	public void setUserCardNo(java.lang.String userCardNo) {
		set("userCardNo", userCardNo);
	}
	
	public java.lang.String getUserCardNo() {
		return getStr("userCardNo");
	}

	public void setPayType(java.lang.String payType) {
		set("payType", payType);
	}
	
	public java.lang.String getPayType() {
		return getStr("payType");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}

	public void setOriginalOrderNo(java.lang.String originalOrderNo) {
		set("originalOrderNo", originalOrderNo);
	}
	
	public java.lang.String getOriginalOrderNo() {
		return getStr("originalOrderNo");
	}

	public void setMerchOrderNo(java.lang.String merchOrderNo) {
		set("merchOrderNo", merchOrderNo);
	}
	
	public java.lang.String getMerchOrderNo() {
		return getStr("merchOrderNo");
	}

	public void setChannelOrderNo(java.lang.String channelOrderNo) {
		set("channelOrderNo", channelOrderNo);
	}
	
	public java.lang.String getChannelOrderNo() {
		return getStr("channelOrderNo");
	}

	public void setChannelMerchCode(java.lang.String channelMerchCode) {
		set("channelMerchCode", channelMerchCode);
	}
	
	public java.lang.String getChannelMerchCode() {
		return getStr("channelMerchCode");
	}

	public void setChannelSubMerchCode(java.lang.String channelSubMerchCode) {
		set("channelSubMerchCode", channelSubMerchCode);
	}
	
	public java.lang.String getChannelSubMerchCode() {
		return getStr("channelSubMerchCode");
	}

	public void setAmount(java.lang.Long amount) {
		set("amount", amount);
	}
	
	public java.lang.Long getAmount() {
		return getLong("amount");
	}

	public void setMerchFee(java.lang.Long merchFee) {
		set("merchFee", merchFee);
	}
	
	public java.lang.Long getMerchFee() {
		return getLong("merchFee");
	}

	public void setBalance(java.lang.Long balance) {
		set("balance", balance);
	}
	
	public java.lang.Long getBalance() {
		return getLong("balance");
	}

	public void setIsD0(java.lang.Boolean isD0) {
		set("isD0", isD0);
	}
	
	public java.lang.Boolean getIsD0() {
		return get("isD0");
	}

	public void setCoinType(java.lang.String coinType) {
		set("coinType", coinType);
	}
	
	public java.lang.String getCoinType() {
		return getStr("coinType");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goodsName");
	}

	public void setQqPhone(java.lang.String qqPhone) {
		set("qqPhone", qqPhone);
	}
	
	public java.lang.String getQqPhone() {
		return getStr("qqPhone");
	}

	public void setPhoneNo(java.lang.String phoneNo) {
		set("phoneNo", phoneNo);
	}
	
	public java.lang.String getPhoneNo() {
		return getStr("phoneNo");
	}

	public void setAccountName(java.lang.String accountName) {
		set("accountName", accountName);
	}
	
	public java.lang.String getAccountName() {
		return getStr("accountName");
	}

	public void setCardNo(java.lang.String cardNo) {
		set("cardNo", cardNo);
	}
	
	public java.lang.String getCardNo() {
		return getStr("cardNo");
	}

	public void setCardType(java.lang.String cardType) {
		set("cardType", cardType);
	}
	
	public java.lang.String getCardType() {
		return getStr("cardType");
	}

	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}
	
	public java.lang.String getBankName() {
		return getStr("bankName");
	}

	public void setBankNo(java.lang.String bankNo) {
		set("bankNo", bankNo);
	}
	
	public java.lang.String getBankNo() {
		return getStr("bankNo");
	}

	public void setReturnUrl(java.lang.String returnUrl) {
		set("returnUrl", returnUrl);
	}
	
	public java.lang.String getReturnUrl() {
		return getStr("returnUrl");
	}

	public void setNotifyUrl(java.lang.String notifyUrl) {
		set("notifyUrl", notifyUrl);
	}
	
	public java.lang.String getNotifyUrl() {
		return getStr("notifyUrl");
	}

	public void setSettleDate(java.lang.String settleDate) {
		set("settleDate", settleDate);
	}
	
	public java.lang.String getSettleDate() {
		return getStr("settleDate");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

	public void setPayTime(java.lang.String payTime) {
		set("payTime", payTime);
	}
	
	public java.lang.String getPayTime() {
		return getStr("payTime");
	}

	public void setOrderStatus(java.lang.String orderStatus) {
		set("orderStatus", orderStatus);
	}
	
	public java.lang.String getOrderStatus() {
		return getStr("orderStatus");
	}

	public void setNotifyStatus(java.lang.String notifyStatus) {
		set("notifyStatus", notifyStatus);
	}
	
	public java.lang.String getNotifyStatus() {
		return getStr("notifyStatus");
	}

	public void setIsInVirtualAccount(java.lang.Boolean isInVirtualAccount) {
		set("isInVirtualAccount", isInVirtualAccount);
	}
	
	public java.lang.Boolean getIsInVirtualAccount() {
		return get("isInVirtualAccount");
	}

	public void setRespCode(java.lang.String respCode) {
		set("respCode", respCode);
	}
	
	public java.lang.String getRespCode() {
		return getStr("respCode");
	}

	public void setRespMsg(java.lang.String respMsg) {
		set("respMsg", respMsg);
	}
	
	public java.lang.String getRespMsg() {
		return getStr("respMsg");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
